BOARD: resize only ext4 ROMS

diff --git a/board/miyoo/boot/firstboot b/board/miyoo/boot/firstboot
--- a/board/miyoo/boot/firstboot
+++ b/board/miyoo/boot/firstboot
@@ -130,7 +130,7 @@ safe_shutdown_func(){
 	sync
 	sleep 1
 	mount -o remount,ro "${MOUNTDIR}" | tee -a ${LOG}
-	umount /dev/mmcblk0p4 | tee -a ${LOG}
+	umount /dev/mmcblk0p3 | tee -a ${LOG}
 	#umount /dev/mmcblk0p1 | tee -a ${LOG} # this fails
 	sleep 4
 }
@@ -516,19 +516,19 @@ SD_SIZE_IN_GiB=$((SD_SIZE * 512 / 1024 / 1024 / 1024))
 BOOT_SIZE=$(((1016+1) * 1024 / 512)) #bootloader partition=1016K (see `genimage` script in buildroot)
 ## boot_size calculated to 512 byte sector size blocks, adding +1K as a safety measure for roundups (at fatresize we use KibiBits)
 
-#Calculate unallocated left space to expand MAIN:
+#Calculate unallocated left space to expand ROMS partition:
 SD_MAX_UNALL_SIZE="$((${SD_SIZE} - (${P1_SIZE} + ${P2_SIZE} + ${P3_SIZE} + ${P4_SIZE}) - $BOOT_SIZE))"
 SD_MAX_UNALL_SIZE_IN_MiB=$((SD_MAX_UNALL_SIZE * 512 / 1024 / 1024))
 SD_MAX_UNALL_SIZE_IN_GiB=$(echo "scale=1; ${SD_MAX_UNALL_SIZE} * 512 / 1024 / 1024 / 1024" | bc)
 
-#Calculate available space for 4'th partition (MAIN):
+#Calculate available space for 4'th partition (ROMS):
 SD_MAX_AVAIL_SIZE="$((${SD_SIZE} - (${P1_SIZE} + ${P2_SIZE} + ${P3_SIZE}) - $BOOT_SIZE))"
 SD_MAX_AVAIL_SIZE_IN_KiB=$((SD_MAX_AVAIL_SIZE * 512 / 1024))
 
-# Expand_MAIN_Partition-prompt for fatresize the p4 partition if requested
+# Expand_ROMS_Partition-prompt for the p4 (ROMS) EXT4 partition if requested
 RESIZE_COMMENCED=false
 if (dialog --backtitle "MiyooCFW 2.0" --no-shadow --clear --stdout --ok-label YES --cancel-label NO --title "   AUTO-RESIZE" \
-   --colors --pause "\n\n       \Z5Expand MAIN partition?\Zn\n\n   Select an option & press START
+   --colors --pause "\n\n       \Z5Expand ROMS partition?\Zn\n\n   Select an option & press START
    \n\n             \ZbWARNING:\Zn\n       After 10s auto-resize\n   of BTRFS partition will begin." 15 60 10); then
 	clear
 	SD_MAX_AVAIL_SIZE_IN_GiB=$(echo "scale=1; ${SD_MAX_AVAIL_SIZE_IN_KiB} / 1024 / 1024" | bc) #only to inform user about end point for resize
@@ -538,25 +538,31 @@ if (dialog --backtitle "MiyooCFW 2.0" --no-shadow --clear --stdout --ok-label YE
 	SD_MAX_AVAIL_SIZE_IN_GBx10=$(echo "$SD_MAX_AVAIL_SIZE_IN_GB" | tr -d ".")
 	P4_SIZE_IN_GBx10=$(echo "$P4_SIZE_IN_GB" | tr -d ".")
 	#Sanity checks if we don't down- or over-resize partition:
+	RESIZE_ABORT=false
 	if (test "$P4_SIZE_IN_GBx10" -ge "$SD_MAX_AVAIL_SIZE_IN_GBx10" || test "$SD_MAX_UNALL_SIZE_IN_MiB" -le 15); then
-		echo "Your MAIN partition is greater than available space for resizing or you lack unallocated sectors space" | tee -a ${LOG}
+		echo "Your ROMS partition is greater than available space for resizing or you lack unallocated sectors space" | tee -a ${LOG}
 		sleep 1.5
 		RESIZE_ABORT=true
 	fi
-	echo "The full size of your SD is ${SD_SIZE_IN_MiB}MB large" | tee -a ${LOG}
-	echo "Unallocated space available for resizing equals ${SD_MAX_UNALL_SIZE_IN_GiB}GB," | tee -a ${LOG}
-	echo "and more precisely it's ${SD_MAX_UNALL_SIZE_IN_MiB}MB big" | tee -a ${LOG}
-	echo "Resizing the MAIN partition to ${SD_MAX_AVAIL_SIZE_IN_GiB}GB." | tee -a ${LOG}
-	echo "This can take a few seconds." | tee -a ${LOG}
-	umount /dev/mmcblk0p4 | tee -a ${LOG}
-	P4_START_POINT=` parted /dev/mmcblk0 unit MB print | grep '4' | tail -n1 | awk '{print $2}'`
-	parted -a optimal /dev/mmcblk0 --script rm 4  | tee -a ${LOG}
-	parted -a optimal /dev/mmcblk0 --script mkpart primary $P4_START_POINT 100%  | tee -a ${LOG}
-	partx -u /dev/mmcblk0  | tee -a ${LOG}
-	mount /dev/mmcblk0p4 ${HOME} | tee -a ${LOG}
-	btrfs filesystem resize max ${HOME} | tee -a ${LOG}
-	partprobe
-	RESIZE_COMMENCED=true
+	if ! $RESIZE_ABORT; then
+		echo "The full size of your SD is ${SD_SIZE_IN_MiB}MB large" | tee -a ${LOG}
+		echo "Unallocated space available for resizing equals ${SD_MAX_UNALL_SIZE_IN_GiB}GB," | tee -a ${LOG}
+		echo "and more precisely it's ${SD_MAX_UNALL_SIZE_IN_MiB}MB big" | tee -a ${LOG}
+		echo "Resizing the ROMS partition to ${SD_MAX_AVAIL_SIZE_IN_GiB}GB." | tee -a ${LOG}
+		echo "This can take a few seconds." | tee -a ${LOG}
+		umount /dev/mmcblk0p4 | tee -a ${LOG}
+		P4_START_POINT=` parted /dev/mmcblk0 unit MB print | grep '4' | tail -n1 | awk '{print $2}'`
+		parted -a optimal /dev/mmcblk0 --script rm 4  | tee -a ${LOG}
+		parted -a optimal /dev/mmcblk0 --script mkpart primary $P4_START_POINT 100%  | tee -a ${LOG}
+		partx -u /dev/mmcblk0  | tee -a ${LOG}
+		mount /dev/mmcblk0p4 /roms | tee -a ${LOG}
+		resize2fs /dev/mmcblk0p4 | tee -a ${LOG}
+		partprobe
+		RESIZE_COMMENCED=true
+	else
+		echo "ROMS partition resizing was aborted!" | tee -a ${LOG}
+		sleep 2
+	fi
 fi
 
 # Cleanup - delete the temporary file storing variable value
