BOARD: revert back to fat32 for MAIN & ext4 for ROOTFS

diff --git a/board/miyoo/boot/firstboot b/board/miyoo/boot/firstboot
--- a/board/miyoo/boot/firstboot
+++ b/board/miyoo/boot/firstboot
@@ -529,8 +529,21 @@ SD_MAX_AVAIL_SIZE_IN_KiB=$((SD_MAX_AVAIL_SIZE * 512 / 1024))
 RESIZE_COMMENCED=false
 if (dialog --backtitle "MiyooCFW 2.0" --no-shadow --clear --stdout --ok-label YES --cancel-label NO --title "   AUTO-RESIZE" \
    --colors --pause "\n\n       \Z5Expand MAIN partition?\Zn\n\n   Select an option & press START
-   \n\n             \ZbWARNING:\Zn\n       After 10s auto-resize\n   of BTRFS partition will begin." 15 60 10); then
+   \n\n             \ZbWARNING:\Zn\n       After 10s auto-resize\n   of FAT32 partition will begin." 15 60 10); then
 	clear
+	RESIZE_ABORT=false
+	if test "$SD_SIZE_IN_GiB" -gt 128; then
+		if (dialog --clear --stdout --ok-label NO --cancel-label YES --title "   \Zb\Z1WARNING!\Zn" \
+		--colors --pause "\nYour SD card exceeds max. size for auto-resizing! 
+		\n\nWe could however expand it to 118GB. \n\n           \ZuDo you AGREE?\Zn
+		\n\n\ZbINFO: For microSD >128GB big we\n      recommend to use your PC!\Zn" 0 0 30 || test $? -eq 255); then
+			dialog --clear --colors --timeout 2 --msgbox " FAT resizing \ZuABORTED!\Zn" 5 27
+			clear
+			RESIZE_ABORT=true
+		else
+			SD_MAX_AVAIL_SIZE_IN_KiB=123731968
+		fi
+	fi
 	SD_MAX_AVAIL_SIZE_IN_GiB=$(echo "scale=1; ${SD_MAX_AVAIL_SIZE_IN_KiB} / 1024 / 1024" | bc) #only to inform user about end point for resize
 	SD_MAX_AVAIL_SIZE_IN_GB=$(echo "scale=1; ${SD_MAX_AVAIL_SIZE_IN_KiB} * 1024 / 1000 / 1000 / 1000" | bc)
 	P4_SIZE_IN_GB=$(echo "scale=1; ${P4_SIZE} * 512 / 1000 / 1000 / 1000" | bc)
@@ -546,16 +559,22 @@ if (dialog --backtitle "MiyooCFW 2.0" --no-shadow --clear --stdout --ok-label YE
 	echo "The full size of your SD is ${SD_SIZE_IN_MiB}MB large" | tee -a ${LOG}
 	echo "Unallocated space available for resizing equals ${SD_MAX_UNALL_SIZE_IN_GiB}GB," | tee -a ${LOG}
 	echo "and more precisely it's ${SD_MAX_UNALL_SIZE_IN_MiB}MB big" | tee -a ${LOG}
-	echo "Resizing the MAIN partition to ${SD_MAX_AVAIL_SIZE_IN_GiB}GB." | tee -a ${LOG}
-	echo "This can take a few seconds." | tee -a ${LOG}
-	umount /dev/mmcblk0p4 | tee -a ${LOG}
-	P4_START_POINT=` parted /dev/mmcblk0 unit MB print | grep '4' | tail -n1 | awk '{print $2}'`
-	parted -a optimal /dev/mmcblk0 --script rm 4  | tee -a ${LOG}
-	parted -a optimal /dev/mmcblk0 --script mkpart primary $P4_START_POINT 100%  | tee -a ${LOG}
-	partx -u /dev/mmcblk0  | tee -a ${LOG}
-	mount /dev/mmcblk0p4 ${HOME} | tee -a ${LOG}
-	btrfs filesystem resize max ${HOME} | tee -a ${LOG}
-	partprobe
+	if ! $RESIZE_ABORT; then
+		echo "Resizing the MAIN partition to ${SD_MAX_AVAIL_SIZE_IN_GiB}GB." | tee -a ${LOG}
+		echo "This can take A LONG TIME, so be patient." | tee -a ${LOG}
+		umount /dev/mmcblk0p4 | tee -a ${LOG}
+		fsck.fat -y /dev/mmcblk0p4 | tee -a ${LOG}
+		#TODO: fix outputting logs from fatresize stdout
+		fatresize --size="${SD_MAX_AVAIL_SIZE_IN_KiB}"ki -v -p /dev/mmcblk0p4 -n4 | tee -a ${LOG}
+		fsck.fat -y /dev/mmcblk0p4 | tee -a ${LOG}
+		echo -n -e \\xEB\\x58\\x90 > /dev/mmcblk0p4
+		sync
+		mount -t vfat -o rw,sync,utf8 /dev/mmcblk0p4 ${HOME} | tee -a ${LOG}
+	else
+		echo "MAIN fat partition resizing was aborted!" | tee -a ${LOG}
+		sleep 2
+	fi
+	#partprobe
 	RESIZE_COMMENCED=true
 fi
 
@@ -575,6 +594,9 @@ elif $MIYOO_CONFIG; then
 	cp "${HOME}/gmenu2x/input_miyoo.conf" "${HOME}/gmenu2x/input.conf"
 fi
 mount -o remount,ro "${MOUNTDIR}" | tee -a ${LOG}
+
+echo "Renaming ${HOME}/retroarch directory to ${HOME}/.retroarch" | tee -a ${LOG}
+mv "${HOME}/retroarch" "${HOME}/.retroarch" | tee -a ${LOG}
 
 sync
 echo "firstboot script finished." | tee -a ${LOG}
